name: CI/CD
on:
  push:
    branches:
    - main
    paths:
    - "doc/**.md"
    - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Setup Git LFS
      run: |
        sudo apt-get update
        sudo apt-get install git-lfs
        git lfs install
        git lfs pull

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v2
      with:
        mdbook-version: '0.4.10'

    - run: mdbook build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book
